Fixes for broken string comparisons in last release and added extra slack msg changes (including optional commit url attribute)

diff --git a/ecs-deployment b/ecs-deployment
--- a/ecs-deployment
+++ b/ecs-deployment
@@ -29,12 +29,12 @@ fi
 failure () {
     ERROR_MGS="$1"
     echo "ERROR: ${ERROR_MGS}"
-    if [[ $SLACK_NOTIFY=="true" ]] ; then 
+    if [[ $SLACK_NOTIFY == "true" ]] ; then 
         SLACK_PRETEXT="ECS Deployment Failure:"
         SLACK_MESSAGE="${ERROR_MGS}!"
         SLACK_COLOR="#FF0000"
         echo "Posting Slack Notification to WebHook: $SLACK_WEBHOOK";
-        SLACK_PAYLOAD="payload={\"channel\": \"${SLACK_CHANNEL}\", \"username\": \"${SLACK_BOTNAME}\", \"attachments\":[{\"fallback\":\"${SLACK_PRETEXT} ${SLACK_MESSAGE}\", \"pretext\":\"*${SLACK_PRETEXT} ${SLACK_MESSAGE}*\", \"color\":\"${SLACK_COLOR}\", \"mrkdwn_in\":[\"text\", \"pretext\"], \"fields\":[{\"title\":\"Service\", \"value\":\"${SERVICE}\", \"short\":false}, {\"title\":\"Error Mesage\", \"value\":\"${ERROR_MGS}\", \"short\":false}]}] }"
+        SLACK_PAYLOAD="payload={\"channel\": \"${SLACK_CHANNEL}\", \"username\": \"${SLACK_BOTNAME}\", \"attachments\":[{\"fallback\":\"${SLACK_PRETEXT} ${SLACK_MESSAGE}\", \"pretext\":\":fire::fire:*${SLACK_PRETEXT} ${SLACK_MESSAGE}*:fire::fire:\", \"color\":\"${SLACK_COLOR}\", \"mrkdwn_in\":[\"text\", \"pretext\"], \"fields\":[{\"title\":\"Service\", \"value\":\"${SERVICE}\", \"short\":false}, {\"title\":\"Error Mesage\", \"value\":\"${ERROR_MGS}\", \"short\":false}]}] }"
         CURL_RESULT=`curl -s -S -X POST --data-urlencode "$SLACK_PAYLOAD" $SLACK_WEBHOOK`
     fi
     if [[ $RECEIPT == "null" ]] || [[ -z $RECEIPT ]] ; then
@@ -49,7 +49,7 @@ failure () {
 
 # Fetch new message from SQS
 echo "Fetching SQS Message from Queue: $SQS_URL";
-aws sqs receive-message --queue-url $SQS_URL --message-attribute-names "service" --visibility-timeout 300 > $MSGFILE
+aws sqs receive-message --queue-url $SQS_URL --message-attribute-names All --visibility-timeout 300 > $MSGFILE
 
 # Check new message is not empty
 if ! [[ -s $MSGFILE ]] ; then echo "SQS Queue was empty (or Receive Message failed)." && exit 1; fi
@@ -68,6 +68,11 @@ echo "SQS Message Receipt Handle: $RECEIPT";
 # Get service name from message attribute
 SERVICE=`jq < $MSGFILE '.Messages[0]|.MessageAttributes|.service|.StringValue' |tr -d '"'`
 if [[ $SERVICE == "null" ]] || [[ -z $SERVICE ]] ; then failure "SQS Message malformed (Service attribute missing)" && exit 1; fi
+
+# Get commit url from message attribute (if included)
+COMMIT_URL=`jq < $MSGFILE '.Messages[0]|.MessageAttributes|.commit_url|.StringValue' |tr -d '"'`
+if [[ $COMMIT_URL == "null" ]] || [[ -z $COMMIT_URL ]] ; then COMMIT_URL="false" && echo "Commit URL not included."; fi
+
 # Extract task definition to json file
 jq < $MSGFILE '.Messages[0]|.Body' |sed -e 's/"{/{/' |sed -e 's/}\\n"/}\\n/' |sed -e 's/}"/}/' | sed -e 's/\\\"/\"/g' | sed -e 's/\\"/"/g' |sed -e 's/\\n/\n/g' > $JSONFILE
 if ! [[ -s $JSONFILE ]] ; then failure "Task Def JSON is empty" && exit 1; fi
@@ -83,11 +88,13 @@ NEW_TASK_VOLUMES=`jq < $JSONFILE '.volumes'`
 if [[ $NEW_TASK_VOLUMES == "null" ]] || [[ -z $NEW_TASK_VOLUMES ]] ; then failure "Task Definition malformed (Volumes not found)" && exit 1; fi
 
 
-# Get current task definition name from service
-CURRENT_TASK_ARN=`aws ecs describe-services --services $SERVICE --cluster $ECS_CLUSTER | jq .services[0].taskDefinition | tr -d '"'`
-if [[ $CURRENT_TASK_ARN == "null" ]] || [[ -z $CURRENT_TASK_ARN ]] ; then failure "Service ${SERVICE} not found" && exit 1; fi
-CURRENT_TASK=`echo ${CURRENT_TASK_ARN} |cut -d':' -f6-7 |cut -d'/' -f2`
-echo "Current task definition: $CURRENT_TASK";
+# Check service exists (if provided) and get current task definition name
+if ! [[ $SERVICE == "false" ]] ; then
+    CURRENT_TASK_ARN=`aws ecs describe-services --services $SERVICE --cluster $ECS_CLUSTER | jq .services[0].taskDefinition | tr -d '"'`
+    if [[ $CURRENT_TASK_ARN == "null" ]] || [[ -z $CURRENT_TASK_ARN ]] ; then failure "Service ${SERVICE} not found" && exit 1; fi
+    CURRENT_TASK=`echo ${CURRENT_TASK_ARN} |cut -d':' -f6-7 |cut -d'/' -f2`
+    echo "Current task definition: $CURRENT_TASK";
+fi
 
 
 # Register the new task definition, and store its ARN
@@ -112,25 +119,30 @@ SLACK_PRETEXT="ECS Deployment:"
 
 
 # Update the service (if specified)
-if [[ $SERVICE=="false" ]] ; then
+if [[ $SERVICE == "false" ]] ; then
     echo "Service set to FALSE";
     SLACK_MESSAGE="Registered new Task Definition <${TASKDEF_URL}|${NEW_TASKDEF}>"
-    SLACK_PAYLOAD="payload={\"channel\": \"${SLACK_CHANNEL}\", \"username\": \"${SLACK_BOTNAME}\", \"attachments\":[{\"fallback\":\"${SLACK_PRETEXT} ${SLACK_MESSAGE}\", \"pretext\":\"*${SLACK_PRETEXT} ${SLACK_MESSAGE}*\", \"color\":\"${SLACK_COLOR}\", \"mrkdwn_in\":[\"text\", \"pretext\"], \"fields\":[{\"title\":\"Task Definiton\", \"value\":\"${NEW_TASKDEF}\", \"short\":false}]}] }"
 else 
     echo "Updating service: $SERVICE";
     UPDATE=`aws ecs update-service --cluster $ECS_CLUSTER --service $SERVICE --task-definition $NEW_TASKDEF_ARN`
     SLACK_MESSAGE="Service <${SERVICE_URL}|${SERVICE}> updated with new Task Definition <${TASKDEF_URL}|${NEW_TASKDEF}>"
-    SLACK_PAYLOAD="payload={\"channel\": \"${SLACK_CHANNEL}\", \"username\": \"${SLACK_BOTNAME}\", \"attachments\":[{\"fallback\":\"${SLACK_PRETEXT} ${SLACK_MESSAGE}\", \"pretext\":\"*${SLACK_PRETEXT} ${SLACK_MESSAGE}*\", \"color\":\"${SLACK_COLOR}\", \"mrkdwn_in\":[\"text\", \"pretext\"], \"fields\":[{\"title\":\"Service\", \"value\":\"${SERVICE}\", \"short\":false}, {\"title\":\"Task Definiton\", \"value\":\"${NEW_TASKDEF}\", \"short\":false}]}] }"
+fi
+
+# Add Github Commit link if provided
+if ! [[ $COMMIT_URL == "false" ]] ; then
+    COMMIT_ID=`echo ${COMMIT_URL} |sed 's/.*\/\(.*\)$/\1/'`
+    SLACK_MESSAGE="${SLACK_MESSAGE} \nCommit ID: <${COMMIT_URL}|${COMMIT_ID}>"
 fi
 
 # Send Slack Notification (if enabled)
-if [[ $SLACK_NOTIFY=="true" ]] ; then
+if [[ $SLACK_NOTIFY == "true" ]] ; then
     echo "Posting Slack Notification to WebHook: $SLACK_WEBHOOK";
+    SLACK_PAYLOAD="payload={\"channel\": \"${SLACK_CHANNEL}\", \"username\": \"${SLACK_BOTNAME}\", \"attachments\":[{\"fallback\":\"${SLACK_PRETEXT} ${SLACK_MESSAGE}\", \"color\":\"${SLACK_COLOR}\", \"mrkdwn_in\":[\"text\", \"pretext\"], \"fields\":[{\"title\":\"${SLACK_PRETEXT}\", \"value\":\"${SLACK_MESSAGE}\", \"short\":false}]}] }"
     CURL_RESULT=`curl -s -S -X POST --data-urlencode "$SLACK_PAYLOAD" $SLACK_WEBHOOK`
 fi
 
 # Exit now if no service update to wait for
-if [[ $SERVICE=="false" ]] ; then
+if [[ $SERVICE == "false" ]] ; then
     echo "Success, new task definition registered.";
     exit 0
 fi
